name: 13 - Using Caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: "Whether to execute cache step"
      node-version:
        type: choice
        options:
          - "26"
          - "24"
        default: "24"
        description: "Node version"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Download cached dependencies
        id: cache
        if: ${{ inputs.use-cache == true }}
        uses: actions/cache@v6
        with:
          key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
          path: "13-caching/react-app/node_modules"
      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run build
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"